#!/bin/bash

#ts2mkv

FFMPEG=ffmpeg

#DONT_TRANSCODE="-c:v copy"

if [ "$#" -lt 1 ]; then
    echo "USAGE: ts2mkv <input .ts file> [optional output filepath]"
    exit 1
fi

TS_FILE="$1"

OUTPUT_MKV=${TS_FILE%.ts}.mkv
if [ "$#" -gt 1 ]; then
    OUTPUT_MKV=${2}
fi

echo "generating mkv ${OUTPUT_MKV}"

${FFMPEG} -y -i ${TS_FILE} -f lavfi -i "movie=${TS_FILE}[out0+subcc]" -map 0 -map 1:s ${DONT_TRANSCODE} -c:a copy -c:s srt ${OUTPUT_MKV}