#!/bin/bash

# play a channel

AZAP=azap
MPLAYER=mplayer

if [ "$#" -ne 1 ]; then
    echo "USAGE: play <channel>"
    exit 1
fi

CHANNEL="$1"

# get an unoccupied tuner. Return code 0..N is the tuner we use
get.tuner
ADAPTER=$?
MUX=0
DEVICE=/dev/dvb/adapter${ADAPTER}/dvr${MUX}

echo setting tuner ${ADAPTER} to channel "${CHANNEL}"

${AZAP} -a ${ADAPTER} -r -s "${CHANNEL}" &
AZAP_PID=$!

sleep 1

#${MPLAYER} -subcc 0 ${DEVICE}
${MPLAYER} ${DEVICE}

kill $AZAP_PID