#!/bin/bash

# play a channel

AZAP=azap
MPLAYER=mplayer

CARD=0
DEVICE=/dev/dvb/adapter${CARD}/dvr${CARD}
 
if [ "$#" -ne 1 ]; then
    echo "USAGE: play <channel>"
    exit 1
fi

CHANNEL="$1"

echo setting tuner to channel "${CHANNEL}"

${AZAP} -r -s "${CHANNEL}" &
AZAP_PID=$!

sleep 2

${MPLAYER} ${DEVICE}

kill $AZAP_PID