#!/bin/bash

# record a channel for N seconds

AZAP=azap
MPLAYER=mplayer

# the directory this script resides in is used to access other tools
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
GET_TUNER=${CURRENT_DIR}/get.tuner

CARD=0
DEVICE=/dev/dvb/adapter${CARD}/dvr${CARD}
 
if [ "$#" -lt 2 ]; then
    echo "USAGE: vcr <channel> <seconds to record> [program name]"
    exit 1
fi

CHANNEL="$1"
SECONDS=$2
# Optional show name argument
NAME=
if [ "$#" -gt 2 ]; then
    NAME=${3}.
fi
DATE=`date +%-d%b%Y\-%-I%M.%S%p`

OUTFILE=${HOME}/Videos/${NAME}${CHANNEL}.${DATE}.ts

# get an unoccupied tuner. Return code 0..N is the tuner we use
${GET_TUNER}
ADAPTER=$?
MUX=0
DEVICE=/dev/dvb/adapter${ADAPTER}/dvr${MUX}

sleep 1

echo "Using free tuner ${ADAPTER} to record channel ${CHANNEL}"

${AZAP} -a "${ADAPTER}" -r -t "${SECONDS}" -s "${CHANNEL}" &
AZAP_PID=$!

sleep 3

timeout ${SECONDS}s cat ${DEVICE} > "${OUTFILE}"

# not necessary to kill the process as it should have exited approx n seconds ago
#kill $AZAP_PID