#!/bin/bash

# record a channel for N seconds

AZAP=azap
MPLAYER=mplayer

CARD=0
DEVICE=/dev/dvb/adapter${CARD}/dvr${CARD}
 
if [ "$#" -ne 2 ]; then
    echo "USAGE: vcr <channel> <seconds to record>"
    exit 1
fi

CHANNEL="$1"
SECONDS=$2
DATE=`date +%-d%b%Y\-%-I%M.%S%p`

OUTFILE=${HOME}/Videos/${CHANNEL}.${DATE}.ts

# get an unoccupied tuner. Return code 0..N is the tuner we use
get.tuner
ADAPTER=$?
MUX=0
DEVICE=/dev/dvb/adapter${ADAPTER}/dvr${MUX}

sleep 1

echo "Using free tuner ${ADAPTER} to record channel ${CHANNEL}"

${AZAP} -a "${ADAPTER}" -r -t "${SECONDS}" -s "${CHANNEL}" &
AZAP_PID=$!

sleep 3

timeout ${SECONDS}s cat ${DEVICE} > "${OUTFILE}"

# not necessary to kill the process as it should have exited approx n seconds ago
#kill $AZAP_PID